### ISSUE TITLE
Is it possible to run on CPU only? (non-CUDA)

### ISSUE THREAD

**Issue by taewookim** [zoogzog/chexnet#1]
which parts would I have to modify to run the model on CPU  only? (Sorry, relatively new to pytorch)

**Comment by zoogzog** [comment]
I would assume, that it is possible to run on CPU only. I am not proficient in pytorch myself, but I think removing all `model = torch.nn.DataParallel(model).cuda()` and `.cuda()`  in the code should do the trick.

**Comment by zoumt1633** [comment]
just remove all .cuda(), and keep model = torch.nn.DataParallel(model).
