### ISSUE TITLE
When the training data is ready for testing,it happens “RuntimeError: CUDA error: out of memory ”

### ISSUE THREAD

**Issue by stupidBirdFirstFly** [zoogzog/chexnet#25]
![image](https://user-images.githubusercontent.com/46771322/111063749-6dd83900-84eb-11eb-89b1-47662d37ecf9.png)
![image](https://user-images.githubusercontent.com/46771322/111063755-73ce1a00-84eb-11eb-8be1-d84678e97255.png)
Seems to be a problem with the Pytorch version.For me,it's Pytorch-0.4
Has anyone encountered this situation? Thank you very much!

**Comment by BrQKarkac** [comment]
@stupidBirdFirstFly How to fix the problem? which pytorch version solution?
