### ISSUE TITLE
Interpreting heatmap

### ISSUE THREAD

**Issue by taewookim** [zoogzog/chexnet#3]
First of all, thanks for this code. I was completely lost ad now im starting to see some light. I am still a noob when it comes pytorch and CXR

HOw do I interpret the heatmap? Im assuming the redder areas is where the diseases / infections are detected (similar to bounding box in object detection). But how do I get the disease associated w/that red color? 

Is it possible to get bounding box with label [like so](https://github.com/thtang/CheXNet-with-localization/blob/master/output/bb_select.JPG?raw=true)?

**Comment by zoogzog** [comment]
Heatmaps visualize class activation mappings. Basically to build the heatmap the output of the last convolution layer (7x7) is multiplied by the corresponding weights and summed. Red indeed represents a higher response of the NN (presence of the pathology).   

In theory, to build the heatmap for a particular disease it will be necessary to multiply by the weights related to that particular pathology. [Here](https://github.com/metalbubble/CAM) there is some sample code. 

I like your idea of marking the pathologies with bounding boxes, I'll think how to implement that.

**Comment by taewookim** [comment]
awesome. any idea when to expect it?
